# Publish NuGet
# Build, Pack & Publish a NuGet package with dotnet core on project version change
# 
# template used:
# https://github.com/marketplace/actions/publish-nuget

name: Dinah.Core publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Dinah.Core build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 9.0.x
          # Authenticates packages to push to GPR
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --configuration Release
      - name: PushNuget
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      - name: PushGithub
        # The github token is automatically being pulled from the workflow
        run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
